[workspace]
members = ["core"]
resolver = "3"

[workspace.package]
authors = ["Reza Akhavan <reza@akhavan.me>"]
repository = "https://github.com/jedireza/warc"
documentation = "https://docs.rs/crate/warc/"
keywords = ["warc", "web", "archive"]
edition = "2024"
rust-version = "1.85"
readme = "README.md"
license = "MIT"
version = "0.4.0"

[workspace.dependencies]
chrono = "0.4"
indexmap = "2"
libflate = "2"
nom = "8"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
url = "2"
